"""
This page  contains the locators for Auth0 login Page"""
input_org_name = "id:organizationName"
btn_continue = "xpath://button[@type='submit']"
btn_continue_with_bink = "xpath://form/button"
input_email = "xpath://input[@type='email']"
btn_next = "id:idSIButton9"
input_password = "name:passwd"
btn_sign_in = "xpath://input[@type='submit']"
text_enter_env_credentials = "xpath://div/h1[contains(text(),'Enter Environment Credentials')]"
