"""
This page  contains the locators for MID Management Merchant Page
"""

btn_view_plan = "xpath://div[@id='__next']/div/div[2]/main/div[2]/div/div[1]/div[2]/button/div"
btn_add_merchant = "xpath://div[@id='__next']/div/div[2]/main/div[2]/div[2]/div[2]/button/div"
txt_input_merchant_name = "xpath://*[@id='bink-form-field-merchant-name']"
btn_save_add_merchant = "xpath://div[@id='modal-download-target']/div[2]/div/div/div[2]/form/div[4]/button"
btn_merchantpagethreedots_option = "xpath://div[@id='__next']/div/div[2]/main/div[2]/div[2]/div[2]/div/div/button"
btn_option_delete = "xpath://div[@id='__next']/div/div[2]/main/div[2]/div[2]/div[2]/div/div/div[1]/button[5]"
label_plans = "xpath://div[@id='__next']/div/div[2]/main/div[1]/div/a[1]"
btn_threedots_option_nearmerachant = "xpath://div[@id='__next']/div/div[2]/main/div[3]/div/div[1]/div/button"
btn_merchant_editoption = "xpath://div[@id='__next']/div/div[2]/main/div[3]/div/div[1]/div/div[1]/button[1]"
btn_saveChanges = "xpath://div[@id='modal-download-target']/div[2]/div/div/div[2]/form/div[4]/button/div"
btn_option_delete_merchant = "xpath://div[@id='__next']/div/div[2]/main/div[3]/div/div[1]/div/div[1]/button[4]"
btn_delete_merchant = "xpath://div[@id='modal-download-target']/div[2]/div/div/div[2]/form/div[3]/button/div"
