"""
This page  contains the locators for MID Management -Merchants-Locations Page
"""


btn_location = "xpath://*[@id='main-content']/div[2]/nav/button[2]/span"
btn_add_location = "id:Add Locations-button"
input_Location_name = "id:bink-form-field-location-name"
input_location_id = "bink-form-field-location-id"
input_addressLine1 = "id:bink-form-field-location-address-line-1"
input_postcode = "id:bink-form-field-location-address-postcode"
btn_save_location = "xpath://*[@id='Save']"
btn_option_threedots = "xpath://*[@id='Options']/div"
btn_option_delete_Location = "xpath://*[@id='main-content']/div[1]/div[2]/div[2]/div[2]/div/div/div[1]/button[4]"
checkbox_location = "xpath://*[@id='main-content']/div[2]/div/table/tbody/tr/td[2]"
btn_sub_location_tab = "xpath://*[@id='modal-download-target']/div[2]/div/div/div[2]/nav/button[4]"
btn_new_Sub_location = "id:New Sub-location-button"
btn_close_location_page = "xpath://*[@id='modal-download-target']/div[2]/div/div/div[1]/button"
btn_edit_location = "xpath://*[@id='Edit-button']/div"
btn_delete_Location = "id:Delete-button"
txt_message = "xpath://*[@id='modal-download-target']/div[2]/div/div/div[2]/div[2]/div/p"
btn_yesdelete_location = "id:Delete Location"
btn_close_location = "xpath://*[@id='Cancel']/div"
btn_x_location = "xpath://*[@id='modal-download-target']/div[2]/div/div/div[1]/button"
btn_uncheck_physicalLocation = "xpath://*[@id='modal-download-target']/div[2]/div/div/div[2]/div/form/div[1]/input"
