"""
This page  contains the locators for MID Management Merchant Page
"""
btn_view_merchant = "id:View"
btn_addVisa = "id:Add Visa MID"
txt_input_mid_value = "xpath://*[@id='bink-form-field-mid']"
txt_input_bin_value = "name: bin"
btn_Add_mid = "id:Add MID-button"
btn_addMaster = "id:Add Mastercard MID"
btn_AddAmex = "id:Add AMEX MID"
btn_midspagethreedots_option = "xpath://*[@id='Options']/div"
btn_midspage_option_delete = "xpath://*[@id='main-content']/div[1]/div[2]/div[2]/div[2]/div/div/div/div[1]/button[4]"
txt_input_merchant_name = "xpath://*[@id='bink-form-field-merchant-name']"
btn_close = "xpath://*[@id='modal-download-target']/div[2]/div/div/div[1]/button"
checkbox_selectall_mids = "xpath://*[@id='__next']/div/div[2]/main/div[2]/div/table/thead/tr/th[1]/div/input"
btn_reason = "id:bink-form-field-deletion-reason"
btn_delete_mids = "xpath://*[@id='Delete-button']"
btn_delete_close = "xpath://*[@id='modal-download-target']/div[2]/div/div/div[1]/button"
btn_delete_mids_dialog_box = "xpath://html/body/div/div/div[1]/div[2]/div/div/div[2]/section[2]/button"
