"""
This page  contains the locators for MID Management Merchant Page
"""
btn_secondary_mids_tab = "xpath://*[@id='main-content']/div[2]/nav/button[3]"
btn_addVisa_secondary = "id:Add Visa Secondary MID"
input_secondary_mid = "id:bink-form-field-secondary-mid"
btn_add_secondarymid = "id:Add Secondary MID-button"
btn_addmaster_secondary = "id:Add Mastercard Secondary MID"
visa_mid = "xpath://*[@id='main-content']/div[2]/div/table/tbody/tr[1]/td[3]"
btn_locations = "id:Locations"
btn_link_newlocation = "id:Link New Location-button"
list_select_location = "xpath://input[@role='combobox']/../button"
dropdownlist_location = "xpath://ul/li[1]"
btn_save = "id:Save Location"
btn_unlink = "xpath:/html/body/div/div/div[1]/div/div[2]/div/div/div[2]/div[1]/div/section[2]/div/div/div/button"
btn_yesunlink = "xpath://*[@id=' ,Yes, unlink-button']"
btn_delete_mid = "id:Delete-button"
btn_yesDelete_mid = "xpath://*[@id='Delete Secondary MID']/div"
btn_comment = "id:Comments"
btn_edit_comment = "xpath://*[@id='modal-download-target']/div[2]/div/div/div[2]/div[1]/div/" \
                   "div/section[1]/section/div/div/div/div/div[1]/div/div/div[2]/div/div/div[1]/button[1]"
