"""
This page  contains the locators for MID Management Page
"""
btn_new_plan = "xpath://div[@id='__next']/div/div[2]/main/div[1]/button"
input_plan_name = "id:bink-form-field-plan-name"
label_mid = "xpath://p[contains(text(),'MID DIRECTORY')]"
input_plan_id = "name:plan-id"
input_Plan_slug = "name:plan-slug"
btn_add_plan = "xpath:/html/body/div/div/div[1]/div[2]/div/div/div[2]/form/div[5]/button/div"
btn_plan_view = "xpath://div[@id='__next']/div/div[2]/main/div[2]/div/div[1]/div[2]/button"
btn_new_merchant = "xpath://div[contains(text(),'New')]/.."
input_box_name = "name:merchant-name"
btn_threeDots = "xpath://div[@id='__next']/div/div[2]/main/div[2]/div/div[1]/div[1]/div/button"
button_edit = "xpath://div[@id='__next']/div/div[2]/main/div[2]/div/div[1]/div[1]/div/div[1]/button[2]"
button_saveChanges = "//div[@id='modal-download-target']/div[2]/div/div/div[2]/form/div[5]/button/div"
txt_updated_plan_name = "xpath://*[@id='bink-form-field-plan-name']"
btn_delete_plan = "xpath://div[contains(text(),'Delete')]/.."
txt_tile = "xpath://div[@id='__next']/div/div[2]/main/div[2]/div/div[1]/div[2]/p[1]"
txt_planName_to_delete = "xpath://*[@id='bink-form-field-plan-name']"
txt_message_deletePlan = "xpath://p[contains(text(),'Are you sure you want to delete ')]"
label_planName = "xpath://div[@id='__next']/div/div[2]/main/div[2]/div/div[1]/div[2]/p[1]"
btn_delete_plan_three_dot_option = "xpath://div[@id='__next']/div/div[2]/main/div[2]/div/div[1]" \
                                   "/div[1]/div/div[1]/button[6]"
